# Generated by Django 3.1.6 on 2021-02-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameTypes',
            new_name='GameType',
        ),
    ]
